# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

environment:

  global:
      PYTHON: "C:\\conda"
      MINICONDA_VERSION: "latest"
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
      PYTHON_ARCH: "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
                        # of 32 bit and 64 bit builds are needed, move this
                        # to the matrix section.
      TEST_CMD: "python --version"  # TODO(wkentaro)

  matrix:
      - PYTHON_VERSION: "2.7"
        DEBUG: "True"

      - PYTHON_VERSION: "3.6"
        DEBUG: "True"

matrix:
   fast_finish: true

platform:
    - x64

install:

    # Install Miniconda
    - "git clone https://github.com/astropy/ci-helpers.git ci-helpers"
    - "powershell ci-helpers/appveyor/install-miniconda.ps1"

    # Set path again, need to find a way to avoid doing this again
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "activate test"

    # Test that PATH is set correctly
    - "conda --version"
    - "python --version"

    # Install labelme
    - "pip install ."

# Not a .NET project, we build ci-helpers in the install step instead
build: false

test_script:
  - "%CMD_IN_ENV% %TEST_CMD%"

branches:
  only:
    - master
